<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">
		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>Inicio</li>
			<li>Carga</li>
			<li>Gestion de Pedido</li>
		</ol>
	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- START ROW -->
			<div class="row">
				<!-- NEW COL START -->
				<article class="col-sm-12 col-md-12 col-lg-6">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget" id="wid-id-0"
						data-widget-colorbutton="false" data-widget-editbutton="false"
						data-widget-custombutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i>
							</span>
							<h2>CARGAR PEDIDOS</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body">

								<form class="smart-form" id="formulario_generar" name="formulario_generar">
									<fieldset>
										<legend>Subida de tramas</legend>

										<div class="form-group">
											<label class="col-md-2 control-label">Archivo</label>
											<div class="col-md-10">
												<input type="file" class="btn btn-default" id="trama_txt"
													name="trama_txt">
												<p class="help-block">
													<em>*Solo archivos de texto (.txt)</em>
												</p>
												<div id="adjuntos" name="adjuntos" style="display: none;">
													<label>Adjunto:</label> <br>
													<ul class="list-unstyled uploaded-attachment">
														<li><i class="fa fa-file-code-o"></i>&nbsp;&nbsp;<em
															id="document_name" name="document_name"></em></a></li>
													</ul>
												</div>
											</div>
										</div>
									</fieldset>
									<fieldset>

										<div class="form-group">
											<section class="col col-2">
												<a id="procesar" class="btn btn-primary btn-sm"
													style="cursor: pointer;display: none">Procesar</a>
											</section>
										</div>
									</fieldset>

								</form>
							</div>
							<!-- end widget content -->	

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->

				</article>
				<!-- END COL -->
				
				<!-- NEW COL START -->
				<article class="col-sm-12 col-md-12 col-lg-6">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget" id="wid-id-0"
						data-widget-colorbutton="false" data-widget-editbutton="false"
						data-widget-custombutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i>
							</span>
							<h2>CARGAR PEDIDOS</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body">

								<form class="smart-form" id="formulario_generar_excel" name="formulario_generar_excel">
									<fieldset>
										<legend>Subida de excel</legend>

										<div class="form-group">
											<label class="col-md-2 control-label">Archivo</label>
											<div class="col-md-10">
												<input type="file" class="btn btn-default" id="trama_excel"
													name="trama_excel">
												<p class="help-block">
													<em>*Solo archivos excel (.csv)</em>
												</p>
												<div id="adjuntos_excel" name="adjuntos_excel" style="display: none;">
													<label>Adjunto:</label> <br>
													<ul class="list-unstyled uploaded-attachment">
														<li><i class="fa fa-file-code-o"></i>&nbsp;&nbsp;<em
															id="document_name_excel" name="document_name_excel"></em></a>
														</li>
														<li id="registros_view" style="display: none;"><i class="fa fa-bar-chart"></i>&nbsp;&nbsp;<em
															id="numeros_documento" name="numeros_documento"></em></a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</fieldset>
									
									<fieldset>
												<section>
													<label class="label">Elegir</label>
													<div class="row">
														<div class="col col-4">
															<label class="radio state-success"><input type="radio" id="radio1" name="radio" value="1" checked><i></i>Canceladas ATIS</label>
														</div>
														<div class="col col-4">
															<label class="radio state-success"><input type="radio" id="radio2" name="radio" value="2"><i></i>Canceladas CMS</label>
														</div>
														<div class="col col-4">
															<label class="radio state-success"><input type="radio" id="radio3" name="radio" value="3"> <i></i>Ejecutadas</label>
														</div>
													</div>
													<div class="note note-success">Seleccione el tipo de base.</div>			
												</section>
											</fieldset>
									
									
									<fieldset>

										<div class="form-group">
											<section class="col col-4">
												<a id="procesar_excel" class="btn btn-primary btn-sm"
													style="cursor: pointer;display: none">Procesar</a>
												<section class="col col-1" id="icono_reloaded"
													style="display: none;">
													<i class="fa fa-cog fa-spin fa-2x fa-fw"
														style="color: #003341;"></i>
												</section>
												<section class="col col-2" id="icono_reloaded_2"
													style="display: none;">
													<div class="note note-primary">Procesando...</div>
												</section>
											</section>
											
										</div>
									</fieldset>
									
									<section class="col col-6" id="errores" style="display: none;">
											
									</section>
									
									<div style="display: none;" id="resultado_proceso">
										<ul class="list-unstyled uploaded-attachment">
											<li><em><strong>Procesados</strong></em></a>
											</li>
											<li><i class="fa fa-check" style="color: #6fb679;"></i>&nbsp;&nbsp;<em
												 style="color: #6fb679;" id="proceso_bueno" name="proceso_bueno"></em></a>
											</li>
											<li><i class="fa fa-times" style="color:red;"></i>&nbsp;&nbsp;<em style="color:red;" id="proceso_malo" name="proceso_malo" color=""></em></a></li>
										</ul>
									</div>
									
								</form>
							</div>
							<!-- end widget content -->	

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->

				</article>
				<!-- END COL -->

			</div>

			<!-- END ROW -->

		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN PANEL -->
