<!DOCTYPE html>
<html lang="en-us" id="extr-page">
	<head>
		<meta charset="utf-8">
		<title> Telefonica - Aseguramiento </title>
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/smartadmin-production-plugins.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/smartadmin-production.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/smartadmin-skins.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/smartadmin-rtl.min.css"> 
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/your_style.css"> 
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASE_URL ?>views/layout/default/css/demo.min.css">
		<link rel="shortcut icon" href="<?php echo BASE_URL ?>views/layout/default/img/favicon/telefonica.ico" type="image/x-icon">
		<link rel="icon" href="<?php echo BASE_URL ?>views/layout/default/img/favicon/telefonica.ico" type="image/x-icon">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
		<link rel="apple-touch-icon" href="<?php echo BASE_URL ?>views/layout/default/img/splash/sptouch-icon-iphone.png">
		<link rel="apple-touch-icon" sizes="76x76" href="<?php echo BASE_URL ?>views/layout/default/img/splash/touch-icon-ipad.png">
		<link rel="apple-touch-icon" sizes="120x120" href="<?php echo BASE_URL ?>views/layout/default/img/splash/touch-icon-iphone-retina.png">
		<link rel="apple-touch-icon" sizes="152x152" href="<?php echo BASE_URL ?>views/layout/default/img/splash/touch-icon-ipad-retina.png">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<link rel="apple-touch-startup-image" href="<?php echo BASE_URL ?>views/layout/default/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
		<link rel="apple-touch-startup-image" href="<?php echo BASE_URL ?>views/layout/default/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
		<link rel="apple-touch-startup-image" href="<?php echo BASE_URL ?>views/layout/default/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
	
	</head>
	
	<body class="animated fadeInDown">
		<header id="header_telefonica">
			<div id="logo-group">
				<span id="logo"> <img src="<?php echo BASE_URL ?>views/layout/default/img/logo_telefonica.png" alt="SmartAdmin"> </span>
			</div>
			<span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs" style="color: white;font-size: 16px"><strong>GESTION INTEGRAL DEL CLIENTE</strong></span> <!-- <a href="register.html" class="btn btn-danger">Create account</a> --> </span>
		</header>

		<div id="main" role="main">

			<!-- MAIN CONTENT -->
			<div id="content" class="container">
				
				<div class="row">
					<div id="fondo_medio" class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
						
						<div class="row"><h1></h1></div>
						<div class="row"><h1></h1></div>
						<div class="row"><h1></h1></div>
						<div class="row"><h1></h1></div>
						<div class="row"><h1></h1></div>
						
						<h1 class="txt-color-white login-header-big" style="font-size: 46px;"><strong>G I C</strong></h1>
						<div class="hero">

							<div class="pull-left login-desc-box-l">
								<h4 class="paragraph-header txt-color-white"><strong>G</strong>estión <strong>I</strong>ntegral del <strong>C</strong>liente</h4>
								<!-- <div class="login-app-icons">
									<a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
									<a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
								</div> -->
							</div>
							
							<!--  <img src="img/demo/iphoneview.png" class="pull-right display-image" alt="" style="width:210px"> -->

						</div>

						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
								<h5 class="about-heading txt-color-white"></h5>
								<p class="txt-color-white"></p>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
								<h5 class="about-heading txt-color-white"></h5>
								<p class="txt-color-white"></p>
							</div>
						</div>

					</div>
					<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
						<div class="well no-padding">
							<form id="login-form" class="smart-form client-form">
								<header>Control de Acceso</header>
								<fieldset>
									<section>
										<label class="label">Usuario</label>
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<input type="text" name="usuario" id="usuario">
											<b id="user_tooltip" class="tooltip tooltip-top-right" style="display: none"></b>
										</label>
									</section>

									<section>
										<label class="label">Password</label>
										<label class="input"> <i class="icon-append fa fa-lock"></i>
											<input type="password" name="password" id="password">
											<b id="pswd_tooltip" class="tooltip tooltip-top-right" style="display: none"></b> 
										</label>
										<div class="note">
											<a id="pswd_actualizar" style="cursor: pointer;">Olvido su contrase&ntilde;a?</a>
										</div>
									</section>

									<!-- <section>
										<label class="checkbox">
											<input type="checkbox" name="remember" checked="">
											<i></i>Stay signed in</label>
									</section> -->
								</fieldset>
								<footer>
									<button type="button" class="btn btn-primary" id="acceso">Acceder</button>
								</footer>
							</form>

						</div>
						
						<h5 class="text-center"> - Siguenos en redes sociales -</h5>							
							<ul class="list-inline text-center">
								<li>
									<a href="https://www.facebook.com/telefonicaperu/" target="_blank" class="btn btn-primary btn-circle" title="Facebook"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="https://twitter.com/telefonica" target="_blank" class="btn btn-info btn-circle" title="Twitter"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="http://pe.linkedin.com/company/telef%C3%B3nica" target="_blank" class="btn btn-warning btn-circle" title="LinkedIn"><i class="fa fa-linkedin"></i></a>
								</li>
							</ul>
					</div>
				</div>
			</div>

		</div>
	</body>
	
	<!-- Change Pasword -->
<div style="display: none;" id="addtab" title="<div  class='widget-header'><h4><i class='fa fa-retweet'></i> Restablecer Contrase&ntilde;a</h4></div>">
<form id="smart-form-register" class="smart-form client-form">
	<fieldset>
		<section>
			<div class="form-group">
				<p>*Por medidas de seguridad es necesario que ingrese su <strong>USUARIO</strong> y <strong>DNI</strong></p>
			</div>
		</section>
		<br>
		<section>
			<div class="form-group">
				<label class="input" id="validacion_usuario"> <i class="icon-append fa fa-github-alt"></i> <input
					type="text" id="usuario_olvido" name="usuario_olvido"
					placeholder="*Usuario"> 
				</label>
			</div>
		</section>
		<section>
			<div class="form-group">
				<label class="input" id="validacion_documento"> <i class="icon-append fa fa-credit-card"></i> <input
					type="text" id="dni_olvido" name="dni_olvido"
					placeholder="*DNI">
				</label>
			</div>
		</section>
	</fieldset>
</form>
</div>

<script data-pace-options='{ "restartOnRequestAfter": true }' src="<?php echo BASE_URL ?>views/layout/default/js/plugin/pace/pace.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script>
			if (!window.jQuery) {
				document.write('<script src="<?php echo BASE_URL ?>views/layout/default/js/libs/jquery-2.1.1.min.js"><\/script>');
			}
		</script>
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
		<script>
			if (!window.jQuery.ui) {
				document.write('<script src="<?php echo BASE_URL ?>views/layout/default/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
			}
		</script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/app.config.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> 
		<script src="<?php echo BASE_URL ?>views/layout/default/js/bootstrap/bootstrap.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/notification/SmartNotification.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/smartwidgets/jarvis.widget.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/sparkline/jquery.sparkline.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/jquery-validate/jquery.validate.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/select2/select2.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/fastclick/fastclick.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/datatables/jquery.dataTables.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/datatables/dataTables.colVis.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/datatables/dataTables.tableTools.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/datatables/dataTables.bootstrap.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/datatable-responsive/datatables.responsive.min.js"></script>
		<script src="<?php echo BASE_URL ?>public/assets/moment/moment.min.js"></script> 
		<script src="<?php echo BASE_URL ?>views/layout/default/js/app.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/smart-chat-ui/smart.chat.ui.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/smart-chat-ui/smart.chat.manager.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/plugin/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
		<script src="<?php echo BASE_URL ?>views/layout/default/js/jquerystrength/dist/pwstrength-bootstrap.min.js"></script>
		
		<?php if(isset($_layoutParams['js']) && count($_layoutParams['js'])): ?>
		<?php foreach($_layoutParams['js'] as $layout): ?>
   			<script src="<?php echo  $layout ?>" type="text/javascript"></script>
		<?php endforeach; ?>
		<?php endif; ?>  
</html>