<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">
		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>Administracion</li>
			<li>Panel</li>
			<li>Panel de Administracion</li>
		</ol>
	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- START ROW -->
			<div class="row">

				<!-- NEW COL START -->
				<article class="col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget" id="wid-id-0"
						data-widget-colorbutton="false" data-widget-editbutton="false"
						data-widget-custombutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i>
							</span>
							<h2>PEDIDOS</h2>

						</header>

						<!-- widget div-->
						<div>
							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body">

								<form class="smart-form">
									<header> Consulta de Pedido </header>

									<fieldset>
										<div class="row">
										   <section class="col col-1">
										   <label class="label">Pedido</label>
										   </section>
										   <section class="col col-2">
													<label class="select">
														<select class="input-sm" id="criterios">
															<option value="0">SELECCIONE</option>
															<option value="1">DNI</option>
															<option value="2">PETICION</option>
														</select> <i></i> 
														<b id="combo_tooltip" class="tooltip tooltip-top-right" style="display: none"></b>
													 </label>
											</section>
											<section class="col col-2">
												<label class="input">
													<input id="criterio_digitar" type="text" placeholder="Criterio*" class="input-sm">
													<b id="criterio_tooltip" class="tooltip tooltip-top-right" style="display: none"></b>
												</label>
											</section>
											<section class="col col-2">
												<a id="buscar" class="btn btn-success btn-sm" style="background-color: #48c400;cursor: pointer;">Buscar</a>
											</section>
											
											<section class="col col-1">
												<a id="derivar_si" title='Derivar' class='btn btn-danger btn-sm' style='display:none;background-color: red'>Derivar</a>
											</section>
										</div>
									</fieldset>
										<br>
										<!-- <fieldset> -->
										<!-- widget div-->
										<div id="contenedor_oculto" style="display: none;">
											<!-- widget content -->
											<div class="widget-body ">
												<table id="dt_basic"
													class="table table-bordered" cellspacing="0">
													<thead>
														<tr>
															<th data-class="expand"><i
																class="fa fa-fw fa-shopping-basket text-muted hidden-md hidden-sm hidden-xs"></i>Codigo de Pedido</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-line-chart text-muted hidden-md hidden-sm hidden-xs"></i>
																Situacion Inicial</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Llamada</th>
															<th><i
																class="fa fa-fw fa-bar-chart text-muted hidden-md hidden-sm hidden-xs"></i>Situacion Ultima</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Registro</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Accion</th>
															<th data-hide="phone"><i
																class="fa fa-fw fa-tasks text-muted hidden-md hidden-sm hidden-xs"></i>
																Opciones</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
											<!-- end widget content -->
										</div>
										<!-- end widget div -->

									<!-- </fieldset> -->
								<!-- ui-dialog -->						
								</form>
							</div>
							<!-- end widget content -->	

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->

				</article>
				<!-- END COL -->

			</div>

			<!-- END ROW -->

		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN PANEL -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th data-class="expand">Codigo de Pedido</th>
													<th data-hide="phone,tablet">Documento</th>
													<th data-hide="phone,tablet">Estado Gestion</th>
													<th data-hide="phone,tablet">Detalle de Gestion</th>
													<th data-hide="phone,tablet">Sub Detalle de Gestion</th>
													<th data-hide="phone,tablet">Observacion Gestion</th>
													<th data-hide="phone,tablet">Pedido Vuelo</th>
													<th data-hide="phone,tablet">Dependencia</th>
													<th data-hide="phone,tablet">Fecha Llamada</th>
													<th>Situacion</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="myModalbase" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabelbase"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_base" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th data-class="expand">Documento</th>
													<th data-hide="phone,tablet">Tipo Operacion</th>
													<th data-hide="phone,tablet">Codigo OC</th>
													<th data-hide="phone,tablet">Producto</th>
													<th data-hide="phone,tablet">Fecha Registro</th>
													<th data-hide="phone,tablet">Fecha Accion</th>
													<th data-hide="phone,tablet">Motivo</th>
													<th data-hide="phone,tablet">Observaciones</th>
													<th>Situacion</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel2"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_aseguramiento" class="table table-striped table-bordered table-hover dt-responsive display nowrap" cellspacing="0">
											<thead>
												<tr>
													<th data-class="expand">Gestion</th>
													<th data-hide="phone,tablet">Codigo Pedido</th>
													<th data-hide="phone,tablet">Motivo</th>
													<th data-hide="phone,tablet">Observacion</th>
													<th data-hide="phone,tablet">Tematico 1</th>
													<th data-hide="phone,tablet">Tematico 2</th>
													<th data-hide="phone,tablet">Tematico 3</th>
													<th data-hide="phone,tablet">Tematico 4</th>
													<th data-hide="phone,tablet">Observacion Gestion</th>
													<th data-hide="phone,tablet">Fecha Carga</th>
													<th data-hide="phone,tablet">Fecha Gestion</th>
													<th data-hide="phone,tablet">Situacion</th>
													<th data-hide="phone,tablet">Usuario</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="myModal_tec" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<div class="col-md-6">
					<h4 class="modal-title" id="myModalLabel_tec"></h4>
					<input id="codigo_pedido_tec" style="display: none;">
				</div>
				<div class="col-md-6">
					<a title='Derivar' id='derivacion_tec' class='fa fa-mail-forward'  style='cursor: pointer;display:inline;color: red;font-size:20px'></a>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<a title='Reiterados' id='reiteracion_tec' class='fa fa-bar-chart-o'  style='cursor: pointer;display:inline;color: #3276b1;font-size:20px'></a>
					<label id="conteo_reiterados"></label>
				</div>
			</div>
			<div class="modal-body">
			<fieldset>
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Tipo: </strong></label>
							<label id="tipo_tec" class="col-md-8 control-label"></label>		
						</div>
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Contacto:</strong> </label>
							<label id="contacto_tec" class="col-md-8 control-label"></label>		
						</div>
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Telefono 1</strong></label>
							<label id="telefono1_tec" class="col-md-8 control-label"></label>		
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Telefono 2</strong></label>
							<label id="telefono2_tec" class="col-md-8 control-label"></label>
						</div>
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Casuistica: </strong></label>
							<label id="casuistica_tec" class="col-md-8 control-label"></label>		
						</div>
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Motivo: </strong></label>
							<label id="motivo_tec" class="col-md-8 control-label"></label>		
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Fecha Agenda: </strong></label>
							<label id="fagenda_tec" class="col-md-8 control-label"></label>		
						</div>
						<div class="col-md-4">
							<label class="col-md-4 control-label"><strong>Hora Agenda: <strong></label>
							<label id="hagenda_tec" class="col-md-8 control-label"></label>		
						</div>
					</div>
					
					<div class="row">
						<div class="col-md-6">
							<label class="col-md-4 control-label"><strong>Observaci&oacute;n</strong></label>
							<label id="observacion_tec" class="col-md-8 control-label"></label>		
						</div>
						<div class="col-md-6">
							<label class="col-md-4 control-label"><strong>Direcci&oacute;n</strong></label>
							<label id="direccion_tec" class="col-md-8 control-label"></label>
						</div>
					</div>
				</div>
				</fieldset>
							
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_tec" class="table table-striped table-bordered table-hover dt-responsive display nowrap" cellspacing="0">
											<thead>
												<tr style="font-weight: normal;">
													<th data-class="expand">Origen</th>
													<th data-hide="phone,tablet">Actividad</th>
													<th data-hide="phone,tablet">casuistica</th>
													<th data-hide="phone,tablet">motivo</th>
													<th data-hide="phone,tablet">Tematico 1</th>
													<th data-hide="phone,tablet">Tematico 2</th>
													<th data-hide="phone,tablet">Tematico 3</th>
													<th data-hide="phone,tablet">Tematico 4</th>
													<th data-hide="phone,tablet">Observacion Gestion</th>
													<th data-hide="phone,tablet">Nuevo Ped</th>
													<th data-hide="phone,tablet">Fecha Carga</th>
													<th data-hide="phone,tablet">Fecha Gestion</th>
													<th data-hide="phone,tablet">Situacion</th>
													<th data-hide="phone,tablet">Estado</th>
													<th data-hide="phone,tablet">Motivo</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="modal_derivar" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="titulo_derivar">
					<img src="<?php echo BASE_URL ?>views/layout/default/img/telefonica_logo.png" width="150" alt="SmartAdmin">
					&nbsp;&nbsp;&nbsp;<i class='fa fa-mail-forward'></i> Derivacion TEC 
				</h4>
			</div>
			
			<div class="modal-body no-padding">
			<form class="smart-form" id="formulario_derivar" name="formulario_derivar">
					<fieldset>
						<!-- <section>
							<div class="row">
									<section class="col col-5">
										<label class="toggle state-error"><input type="checkbox"
											name="checkbox-toggle" id="checkbox-toggle"
											name="checkbox-toggle"> <i data-swchon-text="ON"
											data-swchoff-text="OFF"></i><strong>REDES SOCIALES</strong></label>
									</section>
							</div>
						</section> -->
						<input style="display: none;" id="fecha_registro_pendiente" name="fecha_registro_pendiente"> 
						<input style="display: none;" id="dias_pendiente" name="dias_pendiente"> 
						<input id="enviado_boton_derivar" name="enviado_boton_derivar" style="display:none;">
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Pedido</label>
								</section>
								<section class="col col-3">
									<label class="input"> <label class="label" id="pedido_derivar"
										name="pedido_derivar"></label>
										<input style="display: block;" id="pedido_derivar_input" class="form-control input-sm" placeholder="*Pedido" name="pedido_derivar_input"> 
									</label>
								</section>
							</div>
						</section>
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Tematico</label>
								</section>
								<section class="col col-4">
									<label class="select"> <select class="form-control input-sm"
										id="tematico_combo" name="tematico_combo">
											<option value="">SELECCIONE</option>
										<?php foreach($this->tematico as $indice =>$value):?>						
										<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
										<?php  endforeach;?>
								</select> <i></i>
									</label>
								</section>
								<section class="col col-2">
									<label class="label">Motivo</label>
								</section>
								<section class="col col-4">
									<label class="select"> 
									<select class="form-control input-sm"
										id="motivo_combo" name="motivo_combo">
											<option value="">SELECCIONE</option>
									</select> 
									<i></i>
									</label>
								</section>
							</div>
						</section>
						<section id="instalar_oculto" style="display: none;">
							<div class="row">
								<section class="col col-2">
									<label class="label">Nombres Completos</label>
								</section>
								<section class="col col-10">
									<label class="input"> <input type="text" class="input-sm" 
									id="conctacto_instalar" name="conctacto_instalar" placeholder="*Nombre Contacto">
									</label>
								</section>
							</div>
							<div class="row">
								<section class="col col-2">
									<label class="label">Fecha Agenda</label>
								</section>
								<section class="col col-6">
									<div class="form-group">
										<div class="input-group">
											<input type="text" id="fecha_agenda" name="fecha_agenda" placeholder="*Fecha Agenda" class="form-control datepicker" data-dateformat="yy-mm-dd">
											<span class="input-group-addon" style="z-index: 0"><i class="fa fa-calendar"></i></span>
										</div>
											<ul class="list-unstyled uploaded-attachment">
												<li><i class="fa fa-calendar-check-o" id="icono_no_agendar" style="display: none;"></i>&nbsp;&nbsp;<em
													id="agenda_document" name="agenda_document" style="font-size: 11px"></em></a>
												</li>
											</ul>
									</div>
								</section>
								<section class="col col-4">
									<label class="select"> <select class="form-control input-sm"
										id="turno_combo" name="turno_combo">
											<option value="">SELECCIONE</option>
											<option value="Mañana">MA&Ntilde;ANA</option>
											<option value="Tarde">TARDE</option>
										</select> <i></i>
									</label>
								</section>
							</div>
						</section>
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Telefono 1</label>
								</section>
								<section class="col col-4">
									<label class="input"> <input type="text" class="input-sm" 
									id="telefono_derivar" name="telefono_derivar" placeholder="*Telefono Principal" autocomplete="off">
									</label>
								</section>
								<section class="col col-2">
									<label class="label">Telefono 2</label>
								</section>
								<section class="col col-4">
									<label class="input"> <input type="text" class="form-control input-sm" 
									id="telefono_secundario_derivar" name="telefono_secundario_derivar" placeholder="Telefono Secundario" autocomplete="off">
									</label>
								</section>
							</div>
						</section>
						<section id="direccion_ocultar" style="display: none;">
							<div class="row">
								<section class="col col-2">
									<label class="label">Direccion</label>
								</section>
								<section class="col col-10">
									<label class="input"> <label class="label" id="direccion_derivar"
										name="direccion_derivar"></label>
										<input type="text" class="form-control input-sm" id="direccion_derivar_input" 
										name="direccion_derivar_input" placeholder="*Direccion">
									</label>
								</section>
							</div>
						</section>
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Observaciones</label>
								</section>
								<section class="col col-10">
									<label class="textarea textarea-resizable"> <textarea rows="3"
											class=" form-controlcustom-scroll" id="obs_derivar" name="obs_derivar" placeholder="*Observacion"></textarea>
									</label>
								</section>
							</div>
						</section>
					</fieldset>
					<footer>
						<button type="button" class="btn btn-primary" id="btn_enviar"
							name="btn_enviar">Enviar</button>
					</footer>
				</form>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="myModal_reiteradostec" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel_reiterado" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<div class="col-md-12">
					<h4 class="modal-title" id="myModalLabel_reiteradostec"></h4>
				</div>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_reiterado" class="table table-striped table-bordered table-hover dt-responsive display nowrap" cellspacing="0">
											<thead>
												<tr style="font-weight: normal;">
													<th data-class="expand">Tipo</th>
													<th data-hide="phone,tablet">Actividad</th>
													<th data-hide="phone,tablet">Casuistica</th>
													<th data-hide="phone,tablet">Motivo</th>
													<th data-hide="phone,tablet">Observacion</th>
													<th data-hide="phone,tablet">Fecha Registro</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<!-- Change Pasword -->
<div style="display: none;" id="addtab" title="<div  class='widget-header'><h4><i class='fa fa-retweet'></i> Actualizaci&oacute;n de Contrase&ntilde;a</h4></div>">
<form id="smart-form-register" class="smart-form client-form">
	<fieldset>
		<section>
			<div class="form-group">
				<p>*Por medidas de seguridad es necesario cambiar la
					contrase&ntilde;a en el primer ingreso</p>
			</div>
		</section>
		<br>
		<section>
			<div class="form-group">
				<label class="input"> <i class="icon-append fa fa-lock"></i> <input
					type="password" id="pswd" name="pswd"
					placeholder="*Contrase&ntilde;a"> 
				</label>
				<ul class="list-unstyled uploaded-attachment">
					<li style="color: red;display: none;" id="malo_update"><i class="fa fa-times"></i>&nbsp;&nbsp;<em
						id="malo_digitar" name="malo_digitar" style="font-size: 11px"></em></a>
					</li>
				</ul>
			</div>
		</section>
		<section>
			<div class="form-group">
				<label class="input"> <i class="icon-append fa fa-lock"></i> <input
					type="password" id="pswd2" name="pswd2"
					placeholder="*Contrase&ntilde;a">
				</label>
				<ul class="list-unstyled uploaded-attachment">
					<li style="color: red;display: none;" id="malo_update2"><i class="fa fa-times"></i>&nbsp;&nbsp;<em
						id="malo_digitar2" name="malo_digitar2" style="font-size: 11px"></em></a>
					</li>
				</ul>
			</div>
		</section>
	</fieldset>
</form>
</div>
<!-- Change Pasword -->