<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">
		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>Administracion</li>
			<li>Panel</li>
			<li>Panel de Administracion</li>
		</ol>
	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<!-- widget grid -->
		<section id="widget-grid" class="">
			<!-- START ROW -->
			<div class="row">

				<!-- NEW COL START -->
				<article class="col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget" id="wid-id-0"
						data-widget-colorbutton="false" data-widget-editbutton="false"
						data-widget-custombutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i>
							</span>
							<h2>PEDIDOS</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body">

								<form class="smart-form">
									<header> Consulta de Pedido </header>

									<fieldset>
										<div class="row">
										   <section class="col col-1">
										   <label class="label">Pedido</label>
										   </section>
										   <section class="col col-2">
													<label class="select">
														<select class="input-sm" id="criterios">
															<option value="0">SELECCIONE</option>
															<option value="1">DNI</option>
															<option value="2">PETICION</option>
														</select> <i></i> 
														<b id="combo_tooltip" class="tooltip tooltip-top-right" style="display: none"></b>
													 </label>
											</section>
											<section class="col col-2">
												<label class="input">
													<input id="criterio_digitar" type="text" placeholder="Criterio*" class="input-sm">
													<b id="criterio_tooltip" class="tooltip tooltip-top-right" style="display: none"></b>
												</label>
											</section>
											<section class="col col-2">
												<a id="buscar" class="btn btn-success btn-sm" style="background-color: #48c400;cursor: pointer;">Buscar</a>
											</section>
											
											<section class="col col-1">
												<a id="derivar_si" title='Derivar' class='btn btn-danger btn-sm' style='display:none;background-color: red'>Derivar</a>
											</section>
										</div>
									</fieldset>
										<br>
										<!-- <fieldset> -->
										<!-- widget div-->
										<div id="contenedor_oculto" style="display: none;">
											<!-- widget content -->
											<div class="widget-body ">
												<table id="dt_basic"
													class="table table-bordered" cellspacing="0">
													<thead>
														<tr>
															<th data-class="expand"><i
																class="fa fa-fw fa-shopping-basket text-muted hidden-md hidden-sm hidden-xs"></i>Codigo de Pedido</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-line-chart text-muted hidden-md hidden-sm hidden-xs"></i>
																base Inicial</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Llamada</th>
															<th><i
																class="fa fa-fw fa-bar-chart text-muted hidden-md hidden-sm hidden-xs"></i>Base Ultima</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Registro</th>
															<th data-hide="phone,tablet"><i
																class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i>
																Fecha Accion</th>
															<th data-hide="phone"><i
																class="fa fa-fw fa-tasks text-muted hidden-md hidden-sm hidden-xs"></i>
																Opciones</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
											<!-- end widget content -->
										</div>
										<!-- end widget div -->

									<!-- </fieldset> -->
								<!-- ui-dialog -->						
								</form>
							</div>
							<!-- end widget content -->	

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->

				</article>
				<!-- END COL -->

			</div>

			<!-- END ROW -->

		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN PANEL -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th data-class="expand">Codigo de Pedido</th>
													<th data-hide="phone,tablet">Nombres</th>
													<th data-hide="phone,tablet">Documento</th>
													<th data-hide="phone,tablet">Telefono</th>
													<th data-hide="phone,tablet">Estado Gestion</th>
													<th data-hide="phone,tablet">Detalle de Gestion</th>
													<th data-hide="phone,tablet">Sub Detalle de Gestion</th>
													<th data-hide="phone,tablet">Observacion Gestion</th>
													<th data-hide="phone,tablet">Pedido Vuelo</th>
													<th data-hide="phone,tablet">Dependencia</th>
													<th data-hide="phone,tablet">Fecha Llamada</th>
													<th>Situacion</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="myModalbase" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabelbase"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_base" class="table table-striped table-bordered table-hover">
											<thead>
												<tr>
													<th data-class="expand">Documento</th>
													<th data-hide="phone,tablet">Tipo Operacion</th>
													<th data-hide="phone,tablet">Fecha Registro</th>
													<th data-hide="phone,tablet">Fecha Accion</th>
													<th data-hide="phone,tablet">Motivo</th>
													<th data-hide="phone,tablet">Observaciones</th>
													<th>Situacion</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="myModal_tec" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel_tec"></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form class="smart-form">
							<!-- widget div-->
							<div>
								<!-- widget content -->
								<div class="widget-body">
										<table id="dt_modal_tec" class="table table-striped table-bordered table-hover dt-responsive display nowrap" cellspacing="0">
											<thead>
												<tr>
													<th data-class="expand">Gestion</th>
													<th data-hide="phone,tablet">Tipo</th>
													<th data-hide="phone,tablet">Actividad Origen</th>
													<th data-hide="phone,tablet">Motivo</th>
													<th data-hide="phone,tablet">Observacion</th>
													<th data-hide="phone,tablet">Tematico 1</th>
													<th data-hide="phone,tablet">Tematico 2</th>
													<th data-hide="phone,tablet">Tematico 3</th>
													<th data-hide="phone,tablet">Tematico 4</th>
													<th data-hide="phone,tablet">Observacion Gestion</th>
													<th data-hide="phone,tablet">Fecha Carga</th>
													<th data-hide="phone,tablet">Fecha Gestion</th>
													<th data-hide="phone,tablet">Situacion</th>
													<th data-hide="phone,tablet">Usuario</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
								</div>
								<!-- end widget content -->
							</div>
							<!-- end widget div -->
							<!-- ui-dialog -->
						</form>
					</div>
				</div>

			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="modal_derivar" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="titulo_derivar">
					<img src="<?php echo BASE_URL ?>views/layout/default/img/telefonica_logo.png" width="150" alt="SmartAdmin">
					&nbsp;&nbsp;&nbsp;<i class='fa fa-mail-forward'></i> Derivacion TEC
				</h4>
			</div>
			<div class="modal-body no-padding">
			<form class="smart-form" id="formulario_derivar" name="formulario_derivar">
					<fieldset>
						<!-- <section>
							<div class="row">
									<section class="col col-5">
										<label class="toggle state-error"><input type="checkbox"
											name="checkbox-toggle" id="checkbox-toggle"
											name="checkbox-toggle"> <i data-swchon-text="ON"
											data-swchoff-text="OFF"></i><strong>REDES SOCIALES</strong></label>
									</section>
							</div>
						</section> -->
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Pedido</label>
								</section>
								<section class="col col-3">
									<label class="input"> <label class="label" id="pedido_derivar"
										name="pedido_derivar"></label>
										<input style="display: none;" id="pedido_derivar_input" class="input-sm" placeholder="*Pedido" name="pedido_derivar_input"> 
									</label>
								</section>
								<section class="col col-2">
									<label class="label">Telefono</label>
								</section>
								<section class="col col-5">
									<label class="input"> <input type="text" class="input-sm" 
									id="telefono_derivar" name="telefono_derivar" placeholder="*Telefono">
									</label>
								</section>
							</div>
						</section>
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Direccion</label>
								</section>
								<section class="col col-10">
									<label class="input"> <label class="label" id="direccion_derivar"
										name="direccion_derivar"></label>
										<input type="text" class="input-sm" id="direccion_derivar_input" 
										name="direccion_derivar_input" placeholder="Direccion">
									</label>
								</section>
							</div>
						</section>
						<section>
							<div class="row">
								<section class="col col-2">
									<label class="label">Tematico</label>
								</section>
								<section class="col col-3">
									<label class="select"> <select class="input-sm"
										id="tematico_combo" name="tematico_combo">
											<option value="">SELECCIONE</option>
										<?php foreach($this->tematico as $indice =>$value):?>						
										<option value="<?php echo $value[0] ?>"><?php echo $value[1] ?></option>
										<?php  endforeach;?>
								</select> <i></i>
									</label>
								</section>
								<section class="col col-2">
									<label class="label">Observaciones</label>
								</section>
								<section class="col col-5">
									<label class="textarea textarea-resizable"> <textarea rows="3"
											class="custom-scroll" id="obs_derivar" name="obs_derivar" placeholder="*Observacion"></textarea>
									</label>
								</section>
							</div>
						</section>
					</fieldset>
					<footer>
						<button type="button" class="btn btn-primary" id="btn_enviar"
							name="btn_enviar">Enviar</button>
					</footer>
				</form>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->